export enum UserRoleType {
  SUSPENDED = "SUSPENDED",
  TEXTER = "TEXTER",
  SUPERVOLUNTEER = "SUPERVOLUNTEER",
  ADMIN = "ADMIN",
  OWNER = "OWNER",
  SUPERADMIN = "SUPERADMIN"
}

export enum RequestAutoApproveType {
  DO_NOT_APPROVE = "DO_NOT_APPROVE",
  APPROVAL_REQUIRED = "APPROVAL_REQUIRED",
  AUTO_APPROVE = "AUTO_APPROVE"
}
